### DISCUSSION TITLE
Can't setup SQS credentials via credentials file

### DISCUSSION THREAD

**Discussion by Nakilon** [aws/aws-sdk-ruby#2722] [Q&A]
I made a file:
```none
[default]
aws_access_key_id = ...
aws_secret_access_key = ...
region = ru-central1
endpoint = https://message-queue.api.cloud.yandex.net
```
but I get the error when using the "shoryuken" gem:
```none
No region was provided. Configure the `:region` option or export the region name to ENV['AWS_REGION'] (Aws::Errors::MissingRegionError)
```
To debug it I did:
```ruby
Aws.config.update credentials: Aws::SharedCredentials.new(path: "aws.secret")
puts Aws.config[:credentials].to_yaml
```
and it prints
```yaml
--- !ruby/object:Aws::SharedCredentials
path: aws.secret
profile_name: default
credentials: !ruby/object:Aws::Credentials
  access_key_id: ...
  secret_access_key: ...
  session_token: 
```
i.e. it only read the access key.

UPD: `Aws.config.update({region: "ru-central1", endpoint: "https://message-queue.api.cloud.yandex.net"})` does not help.
