### ISSUE TITLE
CloudFormation client incorrectly adds "preSignedUrl"

### ISSUE THREAD

**Issue by jec** [aws/aws-sdk-ruby#1878]
### Issue description

When I call `AWS::CloudFormation::Client#create_stack`, the SDK is apparently adding a `preSignedUrl` to the request. I am attempting to create a resource of type `AWS::RDS::DBInstance` as a cross-region read replica.

The request succeeds, but the creation of the RDS resource fails. In the CloudFormation console, I see this error:

```
Your request does not require the preSignedUrl parameter. Please remove the preSignedUrl parameter and try your request again. (Service: AmazonRDS; Status Code: 400; Error Code: InvalidParameterCombination; Request ID: 3ea69d31-4669-4cff-ad2b-04e2db11a616)
```

This issue could be similar to:
- https://github.com/aws/aws-cli/issues/3156
- https://github.com/aws/aws-sdk-php/issues/1415

### Gem name 

aws-sdk-cloudformation v1.8.0

### Version of Ruby, OS environment

Ruby v2.5.1
macOS High Sierra v10.13.6

### Code snippets / steps to reproduce

My call to the SDK looks like this:

```ruby
AWS::CloudFormation::Client.new(region: 'us-east-2'.create_stack(
  stack_name: stack_name,
  template_body: File.read(template_file),
  parameters: load_parameters,
  on_failure: 'ROLLBACK',
  capabilities: ['CAPABILITY_NAMED_IAM'],
  tags: [{
    key: 'name',
    value: stack_name
  }]
)
```

My RDS instance template looks like this:

```yaml
# ...
Parameters:
  ReplicaDatabase:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceClass: !Ref DbInstanceClass
      DBSubnetGroupName: !Ref DatabaseSubnetGroup
      Engine: postgres
      EngineVersion: !Ref DbEngineVersion
      PubliclyAccessible: false
      SourceDBInstanceIdentifier: !Ref SourceDBInstanceIdentifier
      SourceRegion: us-east-1
      StorageEncrypted: false
      StorageType: gp2
```

This issue could be similar to the following issues in other repos:
- https://github.com/aws/aws-cli/issues/3156
- https://github.com/aws/aws-sdk-php/issues/1415

I can provide a full example to reproduce if needed.
