### ISSUE TITLE
unexpected value at params[:multipart_threshold]

### ISSUE THREAD

**Issue by EnziinSystem** [aws/aws-sdk-ruby#2451]
My environments:

```
ruby '2.7.2'
gem 'rails', '6.1.0'
gem 'aws-sdk-s3', '~> 1.86'
```
And config/storage.yml
```
amazon:
  service: S3
  access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  region: <%= ENV['AWS_S3_REGION'] %>
  bucket: <%= ENV['AWS_S3_BUCKET'] %>
  public: true
  upload:
    multipart_threshold: <%= 50.megabytes %>
```
When I upload an image avatar for any model, it raises an error.

```
unexpected value at params[:multipart_threshold]
```
This is trace:

```
aws-sdk-core (3.110.0) lib/aws-sdk-core/param_validator.rb:15:in `validate!'
aws-sdk-core (3.110.0) lib/aws-sdk-core/plugins/param_validator.rb:25:in `call'
aws-sdk-core (3.110.0) lib/seahorse/client/plugins/raise_response_errors.rb:16:in `call'
aws-sdk-s3 (1.86.0) lib/aws-sdk-s3/plugins/sse_cpk.rb:24:in `call'
aws-sdk-s3 (1.86.0) lib/aws-sdk-s3/plugins/dualstack.rb:30:in `call'
aws-sdk-s3 (1.86.0) lib/aws-sdk-s3/plugins/accelerate.rb:47:in `call'
aws-sdk-core (3.110.0) lib/aws-sdk-core/plugins/jsonvalue_converter.rb:22:in `call'
aws-sdk-core (3.110.0) lib/aws-sdk-core/plugins/idempotency_token.rb:19:in `call'
aws-sdk-core (3.110.0) lib/aws-sdk-core/plugins/param_converter.rb:26:in `call'
aws-sdk-core (3.110.0) lib/seahorse/client/plugins/request_callback.rb:71:in `call'
aws-sdk-core (3.110.0) lib/aws-sdk-core/plugins/response_paging.rb:12:in `call'
aws-sdk-core (3.110.0) lib/seahorse/client/plugins/response_target.rb:24:in `call'
aws-sdk-core (3.110.0) lib/seahorse/client/request.rb:72:in `send_request'
aws-sdk-s3 (1.86.0) lib/aws-sdk-s3/client.rb:11210:in `put_object'
aws-sdk-s3 (1.86.0) lib/aws-sdk-s3/object.rb:1330:in `put'
activestorage (6.1.0) lib/active_storage/service/s3_service.rb:114:in `upload_with_single_part'
activestorage (6.1.0) lib/active_storage/service/s3_service.rb:31:in `block in upload'
activesupport (6.1.0) lib/active_support/notifications.rb:203:in `block in instrument'
activesupport (6.1.0) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activesupport (6.1.0) lib/active_support/notifications.rb:203:in `instrument'
activestorage (6.1.0) lib/active_storage/service.rb:155:in `instrument'
activestorage (6.1.0) lib/active_storage/service/s3_service.rb:27:in `upload'
activestorage (6.1.0) app/models/active_storage/blob.rb:245:in `upload_without_unfurling'
activestorage (6.1.0) lib/active_storage/attached/changes/create_one.rb:26:in `upload' 
```
