### ISSUE TITLE
Error Creating Stack using cloudformation gem

### ISSUE THREAD

**Issue by deivinsontejeda** [aws/aws-sdk-ruby#2809]
### Describe the bug

I have a StepFunction which create a stack with DB, Secret. The stack is created using Lambda function and Ruby SDK `1.73.0`. The RDS is an Aurora Cluster with a instance attached

the weird things is If I run the template from CLI, it works.

### Expected Behavior

I expect the Aurora Cluster being created.

### Current Behavior

The Cloudformation return following error when create stack using Ruby SDK. Looks obvious error but the same template from CLI create the stack 
![image](https://user-images.githubusercontent.com/628513/209883534-f3ecc332-d8d6-4b46-886f-9b0b38abdee8.png)

### Reproduction Steps

Lambda function

```ruby
require 'aws-sdk-cloudformation'
require 'aws-sdk-states'
require 'aws-sdk-secretsmanager'
require 'logger'

# Main entrypoint for Lambda
# This function expect that event has two keys:
#   :tenant_id
#   :token this is for callback parttern
def lambda_handler(event:, context:)
  tenant_id = event['tenant_id']
  stage = ENV.fetch('STAGE')

  cloudformation = Aws::CloudFormation::Client.new
  state = Aws::States::Client.new

  resp = create_stack(cloudformation, tenant_id, stage)

  # wait until finish
  cloudformation.wait_until(:stack_create_complete, { stack_name: resp[:stack_id] })
  logger.info("Stack created: #{resp[:stack_id]}")
  resp[:tenant_id] = tenant_id

rescue Aws::Waiters::Errors::WaiterFailed => e
  logger.error("Failed to created Stack: #{e.message}")
end

# Just create CloudFormation Stack which will add two resouces
#   - Aurora Cluster
#   - SecretsManager with credentials
def create_stack(client, tenant_id, stage)
  stack_name = "tenant-#{tenant_id}"
  secret_name = "secret-#{tenant_id}"

  params = {
    stack_name: stack_name,
    template_body: File.read("#{File.dirname(__FILE__)}/db.yml"),
    parameters: [
      { parameter_key: 'Stage', parameter_value: stage },
      { parameter_key: 'DbPassword', parameter_value: SecureRandom.alphanumeric(20) },
      { parameter_key: 'DbUser', parameter_value: "u_#{SecureRandom.alphanumeric(10)}" },
      { parameter_key: 'TenantId', parameter_value: tenant_id },
      { parameter_key: 'SecretName', parameter_value: secret_name }
    ],
    tags: [
      { key: 'Stage', value: stage }   ],
    timeout_in_minutes: 10,
    capabilities: ['CAPABILITY_NAMED_IAM'],
    on_failure: 'DELETE', # accepts DO_NOTHING, ROLLBACK, DELETE
    client_request_token: 'ClientRequestToken',
    enable_termination_protection: false
  }

  resp = client.create_stack(params)
  { stack_id: resp.stack_id, stack_name: stack_name, secret_name: secret_name }
end

def logger
  logger = Logger.new($stdout)
  logger.level = Logger::INFO
  logger
end
```

The `db.yml`

```yml
AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  Stage:
    Description: Stage
    Default: Staging
    Type: String
    AllowedValues:
      - Uat
      - Production
      - Staging
      - Dev

  DbPassword:
    Description: Secret password for RDS
    Type: String
    NoEcho: True
  DbUser:
    Description: Secret password for RDS
    Type: String
    NoEcho: True
  SecretName:
    Description: Secret Name where sensitive data is saved
    Type: String
  TenantId:
    Description: Tenant ID belongs this stack
    Type: String
  ScalingMinCapacity:
    Description: Minimum Capacity
    Default: 0.5
    Type: Number

  ScalingMaxCapacity:
    Description: Maximum Capacity
    Default: 2
    Type: Number

Conditions:
  StageEqualToProduction: !Equals
    - !Ref Stage
    - Production

Resources:
  DBCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      AvailabilityZones:
        - us-east-1a
        - us-east-1b
        - us-east-1c
      DatabaseName: auroradb
      DBSubnetGroupName:
        Fn::ImportValue: !Sub ${Stage}-RDSSubnetGroup
      EnableHttpEndpoint: true
      Engine: aurora-postgresql
      EngineVersion: 14.5
      StorageEncrypted: true
      MasterUsername: !Ref DbUser
      MasterUserPassword: !Ref DbPassword
      Port: 5432
      VpcSecurityGroupIds:
        - Fn::ImportValue: !Sub ${Stage}-RDSSecurityGroup
      ServerlessV2ScalingConfiguration:
        MinCapacity: !Ref ScalingMinCapacity
        MaxCapacity: !Ref ScalingMaxCapacity
      Tags:
        - Key: Stage
          Value: !Ref Stage
        - Key: TenantId
          Value: !Ref TenantId

  DBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceClass: db.serverless
      DBClusterIdentifier: !Ref DBCluster
      Engine: aurora-postgresql
      MultiAZ: !If [StageEqualToProduction, true, false]

  RDSSecrets:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Ref SecretName
      SecretString: !Join
        - ""
        - - '{"host": "'
          - !GetAtt DBCluster.Endpoint.Address
          - '","username":"'
          - !Ref DbUser
          - '","password":"'
          - !Ref DbPassword
          - '","port":"5432"}'
      Tags:
        - Key: Stage
          Value: !Ref Stage
        - Key: TenantId
          Value: !Ref TenantId
```

### Additional Information/Context

If you run this template from CLI, it works... I mean create all resources described.

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version

aws-sdk-cloudformation

### Environment details (Version of Ruby, OS environment)

ruby2.7
