### ISSUE TITLE
Tests failure

### ISSUE THREAD

**Issue by Flameeyes** [aws/aws-sdk-ruby#281]
```
Failures:

  1) AWS::S3::S3Object#read reading encrypted data with instruction file should call get_object with instruction material location and decrypt with block
     Failure/Error: object.read(:encryption_key => rsa_key,
     NoMethodError:
       undefined method `data' for #<StringIO:0x0006965f2a98c8>
     # ./lib/aws/s3/s3_object.rb:1318:in `get_object'
     # ./lib/aws/s3/s3_object.rb:1325:in `block in get_encrypted_object'
     # ./lib/aws/s3/s3_object.rb:1573:in `block in decryption_cipher'
     # ./lib/aws/s3/s3_object.rb:1711:in `encryption_key_for'
     # ./lib/aws/s3/s3_object.rb:1557:in `decryption_cipher'
     # ./lib/aws/s3/s3_object.rb:1323:in `get_encrypted_object'
     # ./lib/aws/s3/s3_object.rb:1068:in `read'
     # ./spec/aws/s3/s3_object_encrypt_spec.rb:633:in `block (4 levels) in <class:S3>'

Finished in 1 minute 25.69 seconds
12127 examples, 1 failure, 1 pending
```
